Prepare v1.7.0-rc1
decred/release pull request #49
Opened 2021-12-22 23:11 UTC by jrick

Updates dcrd to release-v1.7.0-rc1 tag.

Updates dcrwallet to release-v1.7.0-rc1 tag.

Updates dcrdex to release-v0.4 branch and dcrdex-assets to v0.4.0-rc1
tag.

Updates dcrlnd to master branch.

Updates politeia to v1.3.1 tag.

2021-12-22 23:22 UTC, jrick commented
People are encouraged to build and test this build but this PR will have to wait for at least another update in dcrinstall before it is ready to merge.

2021-12-24 14:46 UTC, chappjc commented
I need to get this in dex 0.4 first: https://github.com/decred/dcrdex/pull/1367 (in a couple house).

2021-12-24 15:27 UTC, chappjc requested changes

2021-12-24 15:27 UTC, chappjc commented on dcrdex/go.mod
> +	decred.org/dcrdex v0.0.0-20211217203335-620a0258b8cd
`decred.org/dcrdex@v0.4.0-rc1` tagged now

2021-12-24 15:27 UTC, chappjc commented on dcrdex/go.mod
> +	decred.org/dcrdex-assets v0.4.0-rc1
You can stick with this for `dcrdex-assets`, or go with [3616e97a72c7ce8](https://github.com/decred/dcrdex-assets/commit/3616e97a72c7ce836b2e51d58dc08f2c4cda211d), which is one commit past rc1 with a minor charts display fix.

2022-01-03 21:59 UTC, alexlyp approved these changes

2022-01-04 02:00 UTC, davecgh approved these changes
>windows: dist "dcrinstall-manifests" manifest hash: SHA256:e2e29c49d3ee17e0d84cc8cd9a32190e27f4ef66af8952b79200e6624804b615 (go version go1.17.5 windows/amd64)
> linux: dist "dcrinstall-manifests" manifest hash: SHA256:e2e29c49d3ee17e0d84cc8cd9a32190e27f4ef66af8952b79200e6624804b615 (go version go1.17.5 linux/amd64)

2022-01-04 11:05 UTC, jholdstock commented
lgtm

```dist "dcrinstall-manifests" manifest hash: SHA256:e2e29c49d3ee17e0d84cc8cd9a32190e27f4ef66af8952b79200e6624804b615 (go version go1.17.5 linux/amd64)```

2022-01-05 19:16 UTC, merged